name: mufiz
version: "0.5.0"
summary: The Official MufiZ compiler
description: |
  MufiZ is a toy programming language that combines the power of a core bytecode compiler written in C, 
  and built alongside the Zig programming language.

base: core20
grade: stable
confinement: strict

parts:
  mufiz:
    plugin: nil
    build-snaps:
      - zig/0.11.0/beta
    source: .
    override-build: |
      zig build -Doptimize=ReleaseSafe

apps:
  mufiz:
    command: zig-out/bin/mufiz
