[["Math"]]
name = "log2"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "log10"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "sin"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "cos"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "tan"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "asin"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "acos"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "atan"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "pow"
return_type = "double"
parameters = ["double", "integer", "complex"]
implemented = true

[["Math"]]
name = "sqrt"
return_type = "double"
parameters = ["double"]
implemented = true

[["Math"]]
name = "abs"
return_type = "double or integer"
parameters = ["double", "integer", "complex"]
implemented = true

[["Math"]]
name = "phase"
return_type = "double"
parameters = ["complex"]
implemented = true


[["Math"]]
name = "ceil"
return_type = "integer"
parameters = ["double"]
implemented = true

[["Math"]]
name = "floor"
return_type = "integer"
parameters = ["double"]
implemented = true

[["Math"]]
name = "round"
return_type = "integer"
parameters = ["double"]
implemented = true

[["Math"]]
name = "pi"
return_type = "double"
parameters = []
implemented = true

[["Math"]]
name = "rand"
return_type = "integer"
parameters = []
implemented = true

[["Conversions"]]
name = "double"
return_type = "double"
parameters = ["integer"]
implemented = true

[["Conversions"]]
name = "int"
return_type = "integer"
parameters = ["double"]
implemented = true

[["Conversions"]]
name = "str"
return_type = "string"
parameters = ["integer", "double"]
implemented = true

[["Time"]]
name = "now"
return_type = "seconds"
parameters = []
implemented = true

[["Time"]]
name = "now_ns"
return_type = "ns"
parameters = []
implemented = true

[["Time"]]
name = "now_ms"
return_type = "ms"
parameters = []
implemented = true

[["File System"]]
name = "create_file"
return_type = "bool"
parameters = ["string"]
implemented = true

[["File System"]]
name = "write_file"
return_type = "bool"
parameters = ["string"]
implemented = true

[["File System"]]
name = "read_file"
return_type = "string"
parameters = ["string"]
implemented = true

[["File System"]]
name = "delete_file"
return_type = "bool"
parameters = ["string"]
implemented = true

[["File System"]]
name = "create_dir"
return_type = "bool"
parameters = ["string"]
implemented = true

[["File System"]]
name = "delete_dir"
return_type = "bool"
parameters = ["string"]
implemented = true

[["Collections"]]
name = "array"
return_type = "array"
parameters = ["nil"]
implemented = true

[["Collections"]]
name = "linked_list"
return_type = "linked_list"
parameters = ["nil"]
implemented = true

[["Collections"]]
name = "hash_table"
return_type = "hash_table"
parameters = ["nil"]
implemented = true

[["Collections"]]
name = "push"
return_type = "nil"
parameters = ["array", "linked_list"]
implemented = true

[["Collections"]]
name = "push_front"
return_type = "nil"
parameters = ["linked_list"]
implemented = true

[["Collections"]]
name = "pop"
return_type = "any"
parameters = ["array", "linked_list"]
implemented = true

[["Collections"]]
name = "pop_front"
return_type = "any"
parameters = ["linked_list"]
implemented = true

[["Collections"]]
name = "nth"
return_type = "any"
parameters = ["array"]
implemented = true

[["Collections"]]
name = "is_empty"
return_type = "bool"
parameters = ["array", "linked_list"]
implemented = true

[["Collections"]]
name = "sort"
return_type = "nil"
parameters = ["array", "linked_list"]
implemented = true

[["Collections"]]
name = "put"
return_type = "nil"
parameters = ["hash_table"]
implemented = true

[["Collections"]]
name = "get"
return_type = "any"
parameters = ["hash_table"]
implemented = true

[["Collections"]]
name = "remove"
return_type = "nil"
parameters = ["hash_table"]
implemented = true

[["Collections"]]
name = "equal_list"
return_type = "bool"
parameters = ["array", "linked_list"]
implemented = true

[["Collections"]]
name = "contains"
return_type = "bool"
parameters = ["array", "linked_list", "hash_table"]
implemented = false

[["Collections"]]
name = "len"
return_type = "integer"
parameters = ["array", "linked_list", "hash_table"]
implemented = false

[["Collections"]]
name = "range"
return_type = "array"
parameters = ["integer", "integer"]
implemented = false

[["Collections"]]
name = "filter"
return_type = "array"
parameters = ["array", "linked_list"]
implemented = false

[["Collections"]]
name = "reverse"
return_type = "nil"
parameters = ["array", "linked_list"]
implemented = false

[["Collections"]]
name = "search"
return_type = "integer"
parameters = ["array", "linked_list"]
implemented = false

