const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 2) {
        std.debug.print("Usage: {s} <output_path>\n", .{args[0]});
        std.process.exit(1);
    }

    const output_path = args[1];

    // Read build.zig.zon to extract version
    const version = try getVersion(allocator);
    defer allocator.free(version);

    const header = try generateHeader(allocator, version);
    defer allocator.free(header);

    // Ensure output directory exists
    if (std.fs.path.dirname(output_path)) |dir| {
        std.fs.cwd().makePath(dir) catch |err| {
            if (err != error.PathAlreadyExists) {
                return err;
            }
        };
    }

    // Write to file
    const file = try std.fs.cwd().createFile(output_path, .{});
    defer file.close();

    try file.writeAll(header);

    std.debug.print("Generated header: {s}\n", .{output_path});
}

fn getVersion(allocator: std.mem.Allocator) ![]const u8 {
    const file = std.fs.cwd().openFile("build.zig.zon", .{}) catch {
        return allocator.dupe(u8, "0.11.0+");
    };
    defer file.close();

    const content = try file.readToEndAlloc(allocator, 10 * 1024 * 1024);
    defer allocator.free(content);

    // Search for .version = "x.y.z" pattern
    if (std.mem.indexOf(u8, content, ".version")) |version_start| {
        const after_version = content[version_start..];
        if (std.mem.indexOf(u8, after_version, "\"")) |first_quote| {
            const after_first = after_version[first_quote + 1 ..];
            if (std.mem.indexOf(u8, after_first, "\"")) |second_quote| {
                return allocator.dupe(u8, after_first[0..second_quote]);
            }
        }
    }

    return allocator.dupe(u8, "0.11.0+");
}

fn generateHeader(allocator: std.mem.Allocator, version: []const u8) ![]const u8 {
    var buffer = std.ArrayList(u8).initCapacity(allocator, 0) catch unreachable;
    defer buffer.deinit(allocator);
    const writer = buffer.writer(allocator);

    try writer.print(
        \\// MufiZ C API Header
        \\// Comprehensive C interface for MufiZ library
        \\// Version: {s}
        \\//
        \\// This file is AUTO-GENERATED by scripts/gen_header.zig
        \\// DO NOT EDIT THIS FILE MANUALLY
        \\// Source: src/c_api.zig
        \\
        \\#ifndef MUFIZ_H
        \\#define MUFIZ_H
        \\
        \\#include <stdint.h>
        \\#include <stdbool.h>
        \\
        \\#ifdef __cplusplus
        \\extern "C" {{
        \\#endif
        \\
        \\// ============================================================================
        \\// Platform-specific export/import macros
        \\// ============================================================================
        \\
        \\#if defined(_WIN32) || defined(__CYGWIN__)
        \\  #if defined(MUFIZ_BUILDING_LIBRARY)
        \\    #define MUFIZ_API __declspec(dllexport)
        \\  #else
        \\    #define MUFIZ_API __declspec(dllimport)
        \\  #endif
        \\#else
        \\  #if defined(__GNUC__) && __GNUC__ >= 4
        \\    #define MUFIZ_API __attribute__((visibility("default")))
        \\  #else
        \\    #define MUFIZ_API
        \\  #endif
        \\#endif
        \\
        \\// ============================================================================
        \\// Constants
        \\// ============================================================================
        \\
        \\// Error codes
        \\#define MUFIZ_OK                      0
        \\#define MUFIZ_ERR_ALREADY_INITIALIZED -1
        \\#define MUFIZ_ERR_NOT_INITIALIZED     -2
        \\#define MUFIZ_ERR_GENERIC             -3
        \\
        \\// Interpreter result codes
        \\#define MUFIZ_INTERPRET_OK            0
        \\#define MUFIZ_INTERPRET_COMPILE_ERROR 65
        \\#define MUFIZ_INTERPRET_RUNTIME_ERROR 70
        \\
        \\// ============================================================================
        \\// Core Library Functions
        \\// ============================================================================
        \\
        \\/**
        \\ * Initialize the MufiZ library.
        \\ * Must be called before any other library functions.
        \\ *
        \\ * @param enable_leak_detection Enable memory leak detection
        \\ * @param enable_tracking Enable memory allocation tracking
        \\ * @param enable_safety Enable memory safety checks
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_init(
        \\    bool enable_leak_detection,
        \\    bool enable_tracking,
        \\    bool enable_safety
        \\);
        \\
        \\/**
        \\ * Deinitialize the MufiZ library.
        \\ * Should be called when the library is no longer needed.
        \\ * This function is idempotent and safe to call multiple times.
        \\ */
        \\MUFIZ_API void mufiz_deinit(void);
        \\
        \\/**
        \\ * Interpret MufiZ source code.
        \\ *
        \\ * @param source Null-terminated string containing MufiZ source code
        \\ * @return Interpreter result code (MUFIZ_INTERPRET_OK, etc.)
        \\ */
        \\MUFIZ_API uint8_t mufiz_interpret(const char *source);
        \\
        \\// ============================================================================
        \\// Memory Management Functions
        \\// ============================================================================
        \\
        \\/**
        \\ * Check if memory leaks were detected.
        \\ *
        \\ * @return true if memory leaks were detected, false otherwise
        \\ */
        \\MUFIZ_API bool mufiz_has_memory_leaks(void);
        \\
        \\/**
        \\ * Print memory statistics to stdout.
        \\ */
        \\MUFIZ_API void mufiz_print_memory_stats(void);
        \\
        \\// ============================================================================
        \\// String Utilities
        \\// ============================================================================
        \\
        \\/**
        \\ * Duplicate a C string using the library's allocator.
        \\ * The returned pointer must be freed with mufiz_free_cstring().
        \\ *
        \\ * @param src Source null-terminated string
        \\ * @return Pointer to duplicated string, or NULL on allocation failure
        \\ */
        \\MUFIZ_API char *mufiz_strdup(const char *src);
        \\
        \\/**
        \\ * Free a C string previously allocated with mufiz_strdup().
        \\ *
        \\ * @param ptr Pointer to the string to free (can be NULL)
        \\ */
        \\MUFIZ_API void mufiz_free_cstring(char *ptr);
        \\
        \\// ============================================================================
        \\// WASM Compatibility Functions
        \\// ============================================================================
        \\
        \\/**
        \\ * Initialize the library with default settings (for WASM).
        \\ */
        \\MUFIZ_API void init_wasm(void);
        \\
        \\/**
        \\ * Interpret MufiZ source code (WASM wrapper).
        \\ *
        \\ * @param source Null-terminated string containing MufiZ source code
        \\ * @return Interpreter result code
        \\ */
        \\MUFIZ_API uint8_t interpret(const char *source);
        \\
        \\/**
        \\ * Deinitialize the library (WASM wrapper).
        \\ */
        \\MUFIZ_API void deinit_wasm(void);
        \\
        \\// ============================================================================
        \\// Package Management Functions
        \\// ============================================================================
        \\
        \\/**
        \\ * Initialize a new MufiZ project in the current directory.
        \\ * Creates mufi.zon and src/main.mufi files.
        \\ *
        \\ * @param project_name Name for the project
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_init(const char *project_name);
        \\
        \\/**
        \\ * Create a new MufiZ project in a new directory.
        \\ * Creates a new directory with mufi.zon and src/main.mufi files.
        \\ *
        \\ * @param project_name Name for the project and directory
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_new(const char *project_name);
        \\
        \\/**
        \\ * Display information about the current project.
        \\ * Prints mufi.zon contents to stdout.
        \\ *
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_info(void);
        \\
        \\/**
        \\ * Run the current project.
        \\ * Executes the entry point specified in mufi.zon.
        \\ *
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_run(void);
        \\
        \\/**
        \\ * Install all project dependencies.
        \\ * Downloads and caches packages specified in mufi.zon.
        \\ *
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_install(void);
        \\
        \\/**
        \\ * Add a dependency to the current project.
        \\ * Updates mufi.zon with the new dependency.
        \\ *
        \\ * @param name Local name for the dependency
        \\ * @param url GitHub repository URL
        \\ * @param version Git tag, branch, or commit hash
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_add_dependency(
        \\    const char *name,
        \\    const char *url,
        \\    const char *version
        \\);
        \\
        \\/**
        \\ * Display package cache statistics.
        \\ * Shows number of cached packages and total size.
        \\ *
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_cache_info(void);
        \\
        \\/**
        \\ * Clear the package cache.
        \\ * Removes all cached packages from ~/.mufiz/cache/
        \\ *
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_cache_clear(void);
        \\
        \\/**
        \\ * Generate HTML documentation for the project.
        \\ * Creates documentation similar to cargo doc and zig doc.
        \\ *
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_pm_docs(void);
        \\
        \\// ============================================================================
        \\// Formatting Functions
        \\// ============================================================================
        \\
        \\/**
        \\ * Format MufiZ source code.
        \\ * Returns a newly allocated string with formatted code.
        \\ * The returned string must be freed with mufiz_free_cstring().
        \\ *
        \\ * @param source Null-terminated string containing MufiZ source code
        \\ * @return Pointer to formatted source string, or NULL on error
        \\ */
        \\MUFIZ_API char *mufiz_format_source(const char *source);
        \\
        \\/**
        \\ * Format a MufiZ file in-place.
        \\ * Reads the file, formats it, and writes it back.
        \\ *
        \\ * @param filepath Path to the MufiZ file to format
        \\ * @return MUFIZ_OK on success, or a negative error code on failure
        \\ */
        \\MUFIZ_API int32_t mufiz_format_file(const char *filepath);
        \\
        \\/**
        \\ * Check if source code needs formatting.
        \\ *
        \\ * @param source Null-terminated string containing MufiZ source code
        \\ * @return 1 if formatting would change the source, 0 if already formatted, -1 on error
        \\ */
        \\MUFIZ_API int32_t mufiz_needs_formatting(const char *source);
        \\
        \\// ============================================================================
        \\// Usage Examples
        \\// ============================================================================
        \\
        \\/*
        \\Example 1: Basic interpreter usage
        \\
        \\    #include "mufiz.h"
        \\    #include <stdio.h>
        \\
        \\    int main(void) {{
        \\        // Initialize the library
        \\        if (mufiz_init(false, false, false) != MUFIZ_OK) {{
        \\            fprintf(stderr, "Failed to initialize MufiZ\n");
        \\            return 1;
        \\        }}
        \\
        \\        // Interpret some code
        \\        uint8_t result = mufiz_interpret("var x = 42; println(x);");
        \\
        \\        if (result != MUFIZ_INTERPRET_OK) {{
        \\            fprintf(stderr, "Interpretation failed\n");
        \\        }}
        \\
        \\        // Clean up
        \\        mufiz_deinit();
        \\        return 0;
        \\    }}
        \\
        \\Example 2: Package management
        \\
        \\    #include "mufiz.h"
        \\
        \\    int main(void) {{
        \\        // Create a new project
        \\        if (mufiz_pm_new("my-project") != MUFIZ_OK) {{
        \\            return 1;
        \\        }}
        \\
        \\        // Add a dependency
        \\        mufiz_pm_add_dependency(
        \\            "http",
        \\            "https://github.com/user/mufiz-http",
        \\            "v1.0.0"
        \\        );
        \\
        \\        // Install dependencies
        \\        mufiz_pm_install();
        \\
        \\        return 0;
        \\    }}
        \\
        \\Example 3: Code formatting
        \\
        \\    #include "mufiz.h"
        \\    #include <stdio.h>
        \\
        \\    int main(void) {{
        \\        const char *source = "var x=10+20;";
        \\
        \\        // Format the source
        \\        char *formatted = mufiz_format_source(source);
        \\        if (formatted) {{
        \\            printf("Formatted: %s\n", formatted);
        \\            mufiz_free_cstring(formatted);
        \\        }}
        \\
        \\        return 0;
        \\    }}
        \\*/
        \\
        \\#ifdef __cplusplus
        \\}}
        \\#endif
        \\
        \\#endif // MUFIZ_H
        \\
    , .{version});

    return buffer.toOwnedSlice(allocator);
}
