const std = @import("std");

pub fn main(init: std.process.Init) !void {
    var arena = std.heap.ArenaAllocator.init(init.gpa);
    defer arena.deinit();
    const allocator = arena.allocator();

    var args_list = try std.ArrayList([]const u8).initCapacity(allocator, 16);
    var args_iter = std.process.Args.Iterator.init(init.minimal.args);
    while (args_iter.next()) |arg| {
        try args_list.append(allocator, try allocator.dupe(u8, arg));
    }
    const args = args_list.items;

    if (args.len < 2) {
        std.debug.print("Usage: gen_header <output_path>\n", .{});
        return;
    }

    const output_path = args[1];

    // Create the header content
    const header = try generateHeader(allocator);
    defer allocator.free(header);

    // Write to file using the Io API
    const file = try std.Io.Dir.cwd().createFile(init.io, output_path, .{});
    defer file.close(init.io);

    var buf: [4096]u8 = undefined;
    var writer = file.writer(init.io, &buf);
    try writer.interface.writeAll(header);
    try writer.flush();

    std.debug.print("Generated header: {s}\n", .{output_path});
}

fn generateHeader(allocator: std.mem.Allocator) ![]const u8 {
    var buffer = try std.ArrayList(u8).initCapacity(allocator, 4096);

    try buffer.appendSlice(allocator,
        \\// MufiZ C API Header
        \\// Comprehensive C interface for MufiZ library
        \\// Version: 0.16.0+
        \\//
        \\// This file is AUTO-GENERATED by scripts/gen_header.zig
        \\// DO NOT EDIT THIS FILE MANUALLY
        \\// Source: src/c_api.zig
        \\
        \\#ifndef MUFIZ_H
        \\#define MUFIZ_H
        \\
        \\#include <stdint.h>
        \\#include <stdbool.h>
        \\#include <stddef.h>
        \\
        \\#ifdef __cplusplus
        \\extern "C" {
        \\#endif
        \\
        \\// ============================================================================
        \\// Platform-specific export/import macros
        \\// ============================================================================
        \\
        \\#if defined(_WIN32) || defined(__CYGWIN__)
        \\  #if defined(MUFIZ_BUILDING_LIBRARY)
        \\    #define MUFIZ_API __declspec(dllexport)
        \\  #else
        \\    #define MUFIZ_API __declspec(dllimport)
        \\  #endif
        \\#else
        \\  #if defined(__GNUC__) && __GNUC__ >= 4
        \\    #define MUFIZ_API __attribute__((visibility("default")))
        \\  #else
        \\    #define MUFIZ_API
        \\  #endif
        \\#endif
        \\
        \\// ============================================================================
        \\// Core Value Type
        \\// ============================================================================
        \\
        \\typedef struct MufiZ_Value {
        \\    uint64_t data;
        \\} MufiZ_Value;
        \\
        \\// ============================================================================
        \\// VM and Runtime
        \\// ============================================================================
        \\
        \\typedef void* MufiZ_VM;
        \\
        \\MUFIZ_API MufiZ_VM mufiz_vm_create(void);
        \\MUFIZ_API void mufiz_vm_destroy(MufiZ_VM vm);
        \\MUFIZ_API void mufiz_vm_reset(MufiZ_VM vm);
        \\
        \\// ============================================================================
        \\// Code Execution
        \\// ============================================================================
        \\
        \\MUFIZ_API MufiZ_Value mufiz_eval(MufiZ_VM vm, const char* code);
        \\MUFIZ_API MufiZ_Value mufiz_eval_file(MufiZ_VM vm, const char* path);
        \\
        \\// ============================================================================
        \\// Cleanup
        \\// ============================================================================
        \\
        \\#ifdef __cplusplus
        \\}
        \\#endif
        \\
        \\#endif // MUFIZ_H
        \\
    );

    return buffer.toOwnedSlice(allocator);
}
