// Auto-generated from src/c_api.zig by scripts/gen_header.zig
// DO NOT EDIT THIS FILE MANUALLY

#ifndef MUFIZ_H
#define MUFIZ_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// Platform-specific export/import macros
#if defined(_WIN32) || defined(__CYGWIN__)
  #if defined(MUFIZ_BUILDING_LIBRARY)
    #define MUFIZ_API __declspec(dllexport)
  #else
    #define MUFIZ_API __declspec(dllimport)
  #endif
#else
  #if defined(__GNUC__) && __GNUC__ >= 4
    #define MUFIZ_API __attribute__((visibility("default")))
  #else
    #define MUFIZ_API
  #endif
#endif

// Constants
#define MUFIZ_OK 0
#define MUFIZ_ERR_ALREADY_INITIALIZED -1
#define MUFIZ_ERR_NOT_INITIALIZED -2
#define MUFIZ_ERR_GENERIC -3

// Function prototypes

MUFIZ_API int32_t mufiz_init(bool enable_leak_detection, bool enable_tracking, bool enable_safety);
MUFIZ_API void mufiz_deinit(void);
MUFIZ_API uint8_t mufiz_interpret(const char * source);
MUFIZ_API bool mufiz_has_memory_leaks(void);
MUFIZ_API void mufiz_print_memory_stats(void);
MUFIZ_API char * mufiz_strdup(const char * src);
MUFIZ_API void mufiz_free_cstring(char * ptr);

#ifdef __cplusplus
}
#endif

#endif // MUFIZ_H
