name: mufiz
version: "0.4.0"
summary: The Official MufiZ compiler
description: |
  MufiZ is a toy programming language that combines the power of a core bytecode compiler written in C, 
  and built alongside the Zig programming language.

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: [amd64, arm64, armhf, powerpc, riscv64]
parts:
  mufiz:
    plugin: nil
    build-snaps:
      - zig/latest/beta
    source: .
    override-build: |
      zig build -Doptimize=ReleaseSafe 
      cp zig-out/bin/mufiz $SNAPCRAFT_PART_INSTALL

apps:
  mufiz:
    command: ./mufiz
